name: Rust

on:
  push:
    branches: [ "rust" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Build documentation
      run: cargo run -- markdown > docs/index.html

    - name: switching from HTTPS to SSH
      run: git remote set-url origin ${{ secrets.ssh }}
    - name: check for changes
      run: git status
    - name: stage changed files
      run: git add .
    - name: commit changed files
      run: git commit -m "Auto updating index.html"
    - name: fetch from rust
      run: git fetch origin rust
    - name: push code to rust
      run: git push origin HEAD:rust